name: facemap
channels:
  - conda-forge
dependencies:
  - python>3.6
  - pip
  - mkl_fft=1.0.10
  - mkl=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - scipy
  - pyqt
  - hdbscan
  - pip:
    - pyqtgraph==0.12.0
    - pyqt5
    - matplotlib
    - natsort
    - opencv_python_headless
    - tqdm
    - umap-learn
    - pandas