name: facemap2
channels:
  - conda-forge
dependencies:
  - python>=3.8.5
  - pip
  - pip:
    - numpy>=1.16
    - scipy
    - scikit-learn
    - tables==3.6.1
    - matplotlib
    - natsort
    - tqdm
    - numba>=0.43.1
    - opencv-python-headless
    - torch>=1.9
    - pandas
    - pyqtgraph>=0.12.0
    - pyqt5
    - pyqt5.sip
    - umap-learn

