name: facemap
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy>=1.16
  - numba>=0.43.1
  - scipy
  - pyqt
  - hdbscan
  - pytables
  - pip:
    - pyqtgraph==0.12.0
    - pyqt5
    - torch>=1.9
    - torchvision==0.12.0
    - matplotlib
    - natsort
    - opencv_python_headless
    - tqdm
    - umap-learn
    - pandas

