name: facemap
dependencies:
  - python>3.5
  - pip
  - ffmpeg
  - av
  - mkl_fft=1.0.10
  - mkl=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - scikit-image
  - pip:
    - PyQt5
    - pyqtgraph
    - natsort
    - pims
    - FaceMap
